<?php
/**
 * Created by PhpStorm.
 * User: lucas
 * Date: 14/03/19
 * Time: 21:18
 */

namespace App\FieldManagers\Lesson;


use App\FieldManager\FieldManager;

class LessonFieldManager extends FieldManager
{
    protected $fields = [
        'section_id' => [
            'rules' => 'integer|exists:sections,id|required',
        ],
        'name' => [
            'rules' => 'string',
        ],
        'content' => [
            'rules' => 'string',
        ],
    ];

    public function index()
    {
        $fields = [
            'section_id' => 'exists:sections,id|required'
        ];
        return $this->rules($fields); // TODO: Change the autogenerated stub
    }

    public function store()
    {
        $fields = [
            'section_id' => 'required',
            'name' => 'required',
            'content' => 'required'
        ];

        return $this->rules($fields);
    }

    public function simpleFilters()
    {
        return [
            [
                'field' => 'name',
                'type' => 'LIKE'
            ],
            [
                'field' => 'section_id',
                'type' => '='
            ]
        ];
    }
}