<?php
/**
 * Created by PhpStorm.
 * User: lucas
 * Date: 19/03/19
 * Time: 18:40
 */

namespace App\Http\Controllers\Forum;


use App\Entities\Lesson\Forum\Question;
use App\Entities\Section\Section;
use App\FieldManagers\Forum\QuestionFieldManager;
use App\Http\Controllers\ApiController;
use App\Traits\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class QuestionController extends ApiController
{
    use ApiResponse;

    public function __construct(Question $model, QuestionFieldManager $fieldManager)
    {
        $this->fieldManager= $fieldManager;
        $this->model = $model;
    }

    /**
     * @OA\Get(
     *     path="/sections/{section_id}/lessons/{lesson_id}/questions",
     *     summary="Lista todas as questões",
     *     operationId="GetQuestions",
     *     tags={"questions"},
     *     @OA\Parameter(
     *         name="section_id",
     *         in="path",
     *         description="Id da sessão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="lesson_id",
     *         in="path",
     *         description="Id da lição",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="includes",
     *         in="query",
     *         description="Faz o include das relações",
     *         required=false,
     *         @OA\Schema(
     *           type="array",
     *           @OA\Items(type="string")
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="user_id",
     *         in="query",
     *         description="Id do usuário",
     *         required=false,
     *         @OA\Schema(
     *           type="string",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question",
     *         in="query",
     *         description="Nome da questão",
     *         required=false,
     *         @OA\Schema(
     *           type="string",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="approved",
     *         in="query",
     *         description="Se a questão foi aprovada",
     *         required=false,
     *        @OA\Schema(
     *           type="number",
     *           enum={0, 1},
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="...",
     *     )
     * )
     */
    public function getQuestions(Request $request, int $section_id, int $lesson_id)
    {
        Section::findOrFail($section_id)
            ->lessons()->findOrFail($lesson_id);

        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Post(
     *     path="/sections/{section_id}/lessons/{lesson_id}/questions",
     *     summary="Cria uma questão",
     *     operationId="PostQuestion",
     *     tags={"questions"},
     *     security={{"apiToken":{}}},
     *     @OA\Parameter(
     *         name="section_id",
     *         in="path",
     *         description="Id da sessão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="lesson_id",
     *         in="path",
     *         description="Id da lição",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question",
     *         in="query",
     *         description="Descrição da questão",
     *         required=true,
     *         @OA\Schema(
     *           type="string",
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="...",
     *     )
     * )
     */
    public function postQuestion(Request $request, int $section_id, int $lesson_id)
    {
        Section::findOrFail($section_id)
            ->lessons()->findOrFail($lesson_id);

        $request->merge(['user_id' => Auth::user()->id]);
        $request->merge(['lesson_id' => $lesson_id]);

        return parent::store($request); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Get(
     *     path="/sections/{section_id}/lessons/{lesson_id}/questions/{question_id}",
     *     summary="Lista uma questão",
     *     operationId="GetQuestion",
     *     tags={"questions"},
     *     @OA\Parameter(
     *         name="section_id",
     *         in="path",
     *         description="Id da sessão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="lesson_id",
     *         in="path",
     *         description="Id da lição",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question_id",
     *         in="path",
     *         description="Id da questão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="...",
     *     )
     * )
     */
    public function getQuestion(int $section_id, int $lesson_id, int $question_id)
    {
        Section::findOrFail($section_id)
            ->lessons()->findOrFail($lesson_id)
            ->questions()->findOrFail($question_id);

        return parent::show($question_id); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Put(
     *     path="/sections/{section_id}/lessons/{lesson_id}/questions/{question_id}",
     *     summary="Atualiza uma questão",
     *     operationId="PutQuestion",
     *     tags={"questions"},
     *     security={{"apiToken":{}}},
     *     @OA\Parameter(
     *         name="section_id",
     *         in="path",
     *         description="Id da sessão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="lesson_id",
     *         in="path",
     *         description="Id da lição",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question_id",
     *         in="path",
     *         description="Id da questão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question",
     *         in="query",
     *         description="Descrição da questão",
     *         required=false,
     *         @OA\Schema(
     *           type="string",
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="...",
     *     )
     * )
     */
    public function putQuestion(Request $request, int $section_id, int $lesson_id, int $question_id)
    {
        $user_id = Auth::user()->id;

        Section::findOrFail($section_id)
            ->lessons()->findOrFail($lesson_id)
            ->questions()->findOrFail($question_id)
            ->user()->findOrFail($user_id);

        $request->merge(['user_id' => Auth::user()->id]);
        $request->merge(['lesson_id' => $lesson_id]);

        return parent::update($request, $question_id); // TODO: Change the autogenerated stub
    }

    /**
     * @OA\Delete(
     *     path="/sections/{section_id}/lessons/{lesson_id}/questions/{question_id}",
     *     summary="Apaga uma questão",
     *     operationId="DeleteQuestion",
     *     tags={"questions"},
     *     security={{"apiToken":{}}},
     *     @OA\Parameter(
     *         name="section_id",
     *         in="path",
     *         description="Id da sessão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="lesson_id",
     *         in="path",
     *         description="Id da lição",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Parameter(
     *         name="question_id",
     *         in="path",
     *         description="Id da questão",
     *         required=true,
     *         @OA\Schema(
     *           type="integer",
     *         )
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="...",
     *     )
     * )
     */
    public function deleteQuestion(int $section_id, int $lesson_id, int $question_id)
    {
        Section::findOrFail($section_id)
            ->lessons()->findOrFail($lesson_id)
            ->questions()->findOrFail($question_id)
            ->user()->findOrFail(Auth::user()->id);

        return parent::destroy($question_id); // TODO: Change the autogenerated stub
    }
}