openapi: 3.0.0
info:
  title: 'My first API'
  contact:
    email: support@example.com
  version: 1.0.0
paths:
  /auth/login:
    post:
      tags:
        - auth
      summary: 'Autenticação de usuário'
      operationId: AuthLogin
      parameters:
        -
          name: email
          in: query
          description: 'E-mail para autenticação'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha para autenticação'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /admin/auth/login:
    post:
      tags:
        - auth
      summary: 'Autenticação da administração'
      operationId: AuthAdminLogin
      parameters:
        -
          name: email
          in: query
          description: 'E-mail para autenticação'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha para autenticação'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ...
  /auth/refresh:
    post:
      tags:
        - auth
      summary: 'Atualiza o token atual do usuário'
      operationId: AuthRefresh
      responses:
        '200':
          description: ...
  /users/me:
    get:
      tags:
        - users
      summary: 'Lista o usuário'
      operationId: GetUser
      responses:
        '200':
          description: ...
      security:
        -
          apiToken: []
    put:
      tags:
        - users
      summary: 'Atualiza o usuário'
      operationId: UpdateUser
      parameters:
        -
          name: document_number
          in: query
          description: 'Documento CPF'
          required: false
          schema:
            type: string
        -
          name: first_name
          in: query
          description: 'Primeiro nome'
          required: true
          schema:
            type: string
        -
          name: last_name
          in: query
          description: 'Ultimo nome'
          required: true
          schema:
            type: string
        -
          name: address_street
          in: query
          description: 'Rua onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: address_number
          in: query
          description: 'Numero da casa do rapaz'
          required: false
          schema:
            type: string
        -
          name: address_city
          in: query
          description: 'Cidade onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: address_state
          in: query
          description: 'Rua onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: email
          in: query
          description: 'E-mail do cidadão'
          required: true
          schema:
            type: string
        -
          name: old_password
          in: query
          description: 'Senha atual do usuário'
          required: false
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Nova senha do usuário'
          required: false
          schema:
            type: string
        -
          name: password_confirmation
          in: query
          description: 'Confirmação da nova senha do usuário'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ...
      security:
        -
          apiToken: []
  /users:
    get:
      tags:
        - users
      summary: 'Lista todas os usuários'
      operationId: GetUsers
      parameters:
        -
          name: includes
          in: query
          description: 'Faz o include das relações '
          required: false
          schema:
            type: array
            items:
              type: string
        -
          name: name
          in: query
          description: 'Nome do usuário'
          required: false
          schema:
            type: string
        -
          name: email
          in: query
          description: 'Email do usuário'
          required: false
          schema:
            type: string
        -
          name: document_number
          in: query
          description: CPF/CNPJ
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ...
    put:
      tags:
        - users
      summary: 'Atualiza um usuário'
      operationId: UpdateUser
      parameters:
        -
          name: document_number
          in: query
          description: 'Documento CPF'
          required: false
          schema:
            type: string
        -
          name: first_name
          in: query
          description: 'Primeiro nome'
          required: false
          schema:
            type: string
        -
          name: last_name
          in: query
          description: 'Ultimo nome'
          required: false
          schema:
            type: string
        -
          name: address_street
          in: query
          description: 'Rua onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: address_number
          in: query
          description: 'Numero da casa do rapaz'
          required: false
          schema:
            type: string
        -
          name: address_city
          in: query
          description: 'Cidade onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: address_state
          in: query
          description: 'Rua onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: email
          in: query
          description: 'E-mail do cidadão'
          required: false
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha do cidadão'
          required: false
          schema:
            type: string
        -
          name: is_admin
          in: query
          description: 'Status de Administrador'
          required: false
          schema:
            type: number
            enum:
              - 0
              - 1
        -
          name: facebook_id
          in: query
          description: 'ID do Facebook'
          required: false
          schema:
            type: number
        -
          name: google_id
          in: query
          description: 'ID do Google'
          required: false
          schema:
            type: number
      responses:
        '200':
          description: ...
    post:
      tags:
        - users
      summary: 'Cria um novo usuário'
      operationId: StoreUser
      parameters:
        -
          name: document_number
          in: query
          description: 'Documento CPF'
          required: true
          schema:
            type: string
        -
          name: first_name
          in: query
          description: 'Primeiro nome'
          required: true
          schema:
            type: string
        -
          name: last_name
          in: query
          description: 'Ultimo nome'
          required: true
          schema:
            type: string
        -
          name: address_street
          in: query
          description: 'Rua onde o rapaz mora'
          required: true
          schema:
            type: string
        -
          name: address_number
          in: query
          description: 'Numero da casa do rapaz'
          required: false
          schema:
            type: string
        -
          name: address_city
          in: query
          description: 'Cidade onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: address_state
          in: query
          description: 'Rua onde o rapaz mora'
          required: false
          schema:
            type: string
        -
          name: email
          in: query
          description: 'E-mail do cidadão'
          required: true
          schema:
            type: string
        -
          name: password
          in: query
          description: 'Senha do cidadão'
          required: true
          schema:
            type: string
        -
          name: is_admin
          in: query
          description: 'Status de Administrador'
          required: true
          schema:
            type: number
            enum:
              - 0
              - 1
      responses:
        '200':
          description: ...
  '/users/{id}':
    get:
      tags:
        - users
      summary: 'Lista um usuário'
      operationId: GetUser
      parameters:
        -
          name: id
          in: path
          description: 'Id do usuário'
          required: true
          schema:
            type: number
      responses:
        '200':
          description: ...
    delete:
      tags:
        - users
      summary: 'Apaga um usuário'
      operationId: DeleteUser
      parameters:
        -
          name: id
          in: path
          description: 'Id do usuário'
          required: true
          schema:
            type: number
      responses:
        '200':
          description: ...
components:
  securitySchemes:
    apiToken:
      type: apiKey
      description: 'Token do client para consumo da API'
      name: Authorization
      in: header
      scheme: bearer
